# ZSH config
#
# DEPS:
# * Debian:
# sudo apt install zsh-autosuggestions zsh-syntax-highlighting fzf


# History size
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/history

# LOCALE
LC_ALL=en_GB.UTF-8


function preexec() {
  timer=${timer:-$SECONDS}
}

function precmd() {
  if [ $timer ]; then
    timer_show=$(($SECONDS - $timer))
    export RPROMPT="%F{cyan}${timer_show}s %{$reset_color%}"
    unset timer
  fi
}


#PS1="%n@%M$ %~ %# "


# PROMPT WITH COLORS
# Color table for 256-color terminal:
# https://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html
PROMPT='%(?.%F{green}√.%F{red}?%?)%f %F{32}%n@%M%f %B%F{249}%1~%f%b %# '


# Basic colors and autocomplete
autoload -U colors && colors
autoload -Uz compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)


# Fish-like syntax highlight
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

ZSH_HIGHLIGHT_STYLES[suffix-alias]=fg=blue,underline
ZSH_HIGHLIGHT_STYLES[precommand]=fg=blue,underline
ZSH_HIGHLIGHT_STYLES[arg0]=fg=blue
#ZSH_HIGHLIGHT_STYLES[alias]=fg=blue,bold
#ZSH_HIGHLIGHT_STYLES[builtin]=fg=blue,bold
#ZSH_HIGHLIGHT_STYLES[function]=fg=blue,bold
#ZSH_HIGHLIGHT_STYLES[command]=fg=white,bold


ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=white,bold,bg=red')


# autosuggestions
#source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOME/.config/zsh/zsh-autosuggestions.zsh

# FZF bindings
source $HOME/.config/zsh/fzf.zsh



# USE lfcd on shell to change directory
# *copied from etc/gen directory on the github repository
lfcd () {
    tmp="$(mktemp)"
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        if [ -d "$dir" ]; then
            if [ "$dir" != "$(pwd)" ]; then
                cd "$dir"
            fi
        fi
    fi
}

bindkey -s '^o' 'lfcd\n' # zsh



# LOAD alias and other configs
source $HOME/.config/apps
source $HOME/.config/alias

# add custom scripts to path
#export PATH=$PATH:$HOME/.config/scripts
#export PATH=$PATH:$HOME/.local/bin

